dist: trusty
sudo: true

# needed for seqware
services:
  - docker

env:
  global:
    - R_LIB_USER=$HOME/R/Library
  matrix:
    - LAUNCH_SCRIPT='run_cromwell.sh'
    - LAUNCH_SCRIPT='run_cwltool.sh'
    - LAUNCH_SCRIPT='run_bash.sh'
    - LAUNCH_SCRIPT='run_toil_cwl.sh'
    - LAUNCH_SCRIPT='run_seqware.sh'

cache:
  directories:
    - $HOME/R/Library
    - perl_modules
    - $HOME/.m2

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq samtools cpanminus r-base

install: 
- cd gsi-website && perl Makefile.PL && make && make test && sudo make install && cd ..
- cd bamqc && cpanm --installdeps --sudo . && perl Makefile.PL && make && make test && sudo make install && cd ..

before_script:
- bash replacepaths.sh

script:
- bash "${LAUNCH_SCRIPT}"
